---
- name: Get whoami of remote host
  ansible.builtin.shell: whoami
  register: custom_whoami

- name: Create SSH directory
  ansible.builtin.file:
    path: "/home/{{ custom_whoami.stdout }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ custom_whoami.stdout }}"
    group: "{{ custom_whoami.stdout }}"


- name: Create empty known_hosts file
  ansible.builtin.copy:
    dest: "/home/{{ custom_whoami.stdout }}/.ssh/known_hosts"
    content: ""
    owner: "{{ custom_whoami.stdout }}"
    group: "{{ custom_whoami.stdout }}"
    mode: '0644'
    force: false

- name: Create empty authorized_keys file
  ansible.builtin.copy:
    dest: "/home/{{ custom_whoami.stdout }}/.ssh/authorized_keys"
    content: ""
    owner: "{{ custom_whoami.stdout }}"
    group: "{{ custom_whoami.stdout }}"
    mode: '0644'
    force: false

- name: Create empty .bashrc file
  ansible.builtin.copy:
    dest: "/home/{{ custom_whoami.stdout }}/.bashrc"
    content: ""
    owner: "{{ custom_whoami.stdout }}"
    group: "{{ custom_whoami.stdout }}"
    mode: '0644'
    force: false
